const test = require('node:test');
const assert = require('node:assert/strict');
const {spawn} = require('node:child_process');
const port = 3417;
let child;
test.before(async()=>{child=spawn(process.execPath,['server.js'],{cwd:__dirname+'/..',env:{...process.env,PORT:String(port),HEBICHESS_BINARY:'../build/HebiChess',DEFAULT_SEARCH_DEPTH:'1'}});await new Promise((resolve,reject)=>{child.stdout.on('data',d=>{if(d.toString().includes('listening'))resolve()});child.on('error',reject)})});
test.after(()=>child.kill());
async function call(path,body,cookie){const r=await fetch(`http://127.0.0.1:${port}${path}`,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(cookie?{cookie}: {})},body:body&&JSON.stringify(body)});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{data=raw}return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie}}
function session(value){return `hebichess_session=${value}`}
function sse(cookie){return fetch(`http://127.0.0.1:${port}/events`,{headers:{cookie}})}
async function firstEvent(response){const reader=response.body.getReader();let text='';for(;;){const {value,done}=await reader.read();if(done)throw Error('SSE closed');text+=Buffer.from(value).toString();const match=text.match(/data: (.+)\n\n/);if(match){reader.releaseLock();return JSON.parse(match[1])}}}
test('session-personalized player, spectator and persistent SSE role',async()=>{let a=await call('/');assert.match(a.cookie,/^hebichess_session=/);const ac=a.cookie,bc=session('spectator-b');a=await call('/api/state',null,ac);assert.equal(a.data.active,false);const streamA=await sse(ac);assert.equal((await firstEvent(streamA)).active,false);a=await call('/api/start',{color:'white'},ac);assert.equal(a.status,200);assert.equal(a.data.role,'player');assert.equal(a.data.isPlayer,true);let b=await call('/api/state',null,bc);assert.equal(b.data.role,'spectator');assert.equal(b.data.isPlayer,false);b=await call('/api/move',{move:'e7e5'},bc);assert.equal(b.status,403);b=await call('/api/move',{move:'e2e5'},ac);assert.equal(b.status,422);b=await call('/api/move',{move:'e2e4'},ac);assert.equal(b.status,200);const refreshed=await call('/api/state',null,ac);assert.equal(refreshed.data.role,'player');assert.equal(refreshed.data.isPlayer,true);b=await call('/api/resign',{},ac);assert.equal(b.status,200);assert.equal((await call('/api/state',null,ac)).data.active,false);assert.equal((await call('/api/state',null,bc)).data.active,false);});
test('SSE connected before start receives player role',async()=>{const ac=session('player-sse');const stream=await sse(ac);assert.equal((await firstEvent(stream)).active,false);const started=await call('/api/start',{color:'white'},ac);assert.equal(started.status,200);const event=await firstEvent(stream);assert.equal(event.role,'player');assert.equal(event.isPlayer,true);await call('/api/resign',{},ac);});
