const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const root = __dirname, PUBLIC_ROOT = path.join(root, 'public') + path.sep;
const PORT = Number(process.env.PORT || 3400), DATA = path.resolve(root, process.env.DATA_PATH || './data/games.json');
const PRODUCTION = process.env.NODE_ENV === 'production';
const games = new Map(), ownedGames = new Map(), clients = new Map();
const files = {'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.wasm':'application/wasm'};
const id = () => crypto.randomUUID();
function cookie(req, res) { const match=(req.headers.cookie||'').match(/hebichess_session=([^;]+)/); if(match)return match[1]; const value=id(); res.setHeader('Set-Cookie',`hebichess_session=${value}; Path=/; HttpOnly; SameSite=Lax${PRODUCTION?'; Secure':''}`); return value; }
function boardStart() { return ['rnbqkbnr','pppppppp','........','........','........','........','PPPPPPPP','RNBQKBNR'].map(row=>row.split('')); }
function initialSnapshot() { return {fen:'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',moves:[],san:[],result:null,termination:null,lastMove:null,history:[]}; }
function whitePovEvaluation(scoreCp, rootSide) { return (rootSide==='b'?-scoreCp:scoreCp)/100; }
function completedRecord(target,result,termination,endedAt) { return {startTime:target.startedAt,endTime:endedAt,playerColor:target.playerColor,moves:target.snapshot.moves,result,termination}; }
function appendCompletedRecord(existing,record) {
  if(Array.isArray(existing))return [...existing,record];
  if(!existing||typeof existing!=='object')throw new TypeError('unsupported games.json schema');
  for(const key of ['games','completedGames','history','records']) { if(Array.isArray(existing[key]))return {...existing,[key]:[...existing[key],record]}; if(existing[key]&&typeof existing[key]==='object'&&!Array.isArray(existing[key]))return {...existing,[key]:{...existing[key],[record.gameId||record.endTime]:record}}; }
  if(existing.gameId||existing.startTime||existing.endTime)return [existing,record]; return {...existing,completedGames:[record]};
}
function persistCompleted(target,result,termination,endedAt) { fs.mkdirSync(path.dirname(DATA),{recursive:true}); let existing=[]; try{existing=JSON.parse(fs.readFileSync(DATA,'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;} const record=completedRecord(target,result,termination,endedAt); fs.writeFileSync(DATA,JSON.stringify(appendCompletedRecord(existing,record),null,2)); return record; }
function stateFor(session,target) {
  if(!target)return {active:false,role:'lobby',isPlayer:false,gameId:null,result:null,termination:null};
  const s=target.snapshot, isPlayer=session===target.playerSessionId;
  return {active:target.active,gameId:target.id,revision:target.revision,role:isPlayer?'player':'spectator',isPlayer,playerColor:target.playerColor,board:s.board||boardStart(),currentFen:s.fen||initialSnapshot().fen,moves:s.moves||[],san:s.san||[],history:s.history||[],turn:(s.fen||' w ').split(' ')[1]||'w',engineThinking:target.engineThinking,result:s.result??s.result??null,termination:target.termination??s.termination??null,lastMove:s.lastMove??s.lastMove??null,checkSquare:s.checkSquare||null,depth:target.depth||0,evaluation:target.evaluation||0,nodes:target.nodes||0,capturedPieces:s.capturedPieces||{w:[],b:[]},startedAt:target.startedAt,createdAt:target.createdAt,updatedAt:target.updatedAt};
}
function emit(target,type) { for(const [response,client] of clients) if(client.gameId===target.id || (client.gameId==null&&client.sessionId===target.playerSessionId)) response.write(`event: ${type}\ndata: ${JSON.stringify(stateFor(client.sessionId,target))}\n\n`); }
function end(target,result,termination) { if(!target||target.result)return; target.result=result; target.termination=termination; target.snapshot.result=result; target.snapshot.termination=termination; target.engineThinking=false; target.active=false; target.revision++; target.updatedAt=new Date().toISOString(); persistCompleted(target,result,termination,target.updatedAt); if(ownedGames.get(target.playerSessionId)===target.id)ownedGames.delete(target.playerSessionId); emit(target,'gameOver'); emit(target,'state'); }
function start(session,colorChoice) { const owned=games.get(ownedGames.get(session)); if(owned?.active)return false; if(owned)ownedGames.delete(session); const playerColor=colorChoice==='black'?'b':colorChoice==='white'?'w':Math.random()<.5?'w':'b'; const now=new Date().toISOString(),snapshot=initialSnapshot(); const target={id:id(),active:true,playerSessionId:session,playerColor,revision:0,snapshot,engineThinking:playerColor==='b',result:null,termination:null,depth:0,evaluation:0,nodes:0,createdAt:now,updatedAt:now,startedAt:now}; games.set(target.id,target); ownedGames.set(session,target.id); emit(target,'state'); return target; }
function requestedGame(session,requestedId) { return requestedId?games.get(requestedId):games.get(ownedGames.get(session)); }
function applySnapshot(target,input) { const snapshot=input.snapshot||input.state; if(!snapshot||typeof snapshot!=='object')return false; if(typeof snapshot.fen!=='string'||!Array.isArray(snapshot.moves)||!Array.isArray(snapshot.san))return false; const {legalMoves: _serverLegalMoves, ...browserSnapshot}=snapshot; target.snapshot={...target.snapshot,...browserSnapshot,gameId:target.id}; target.lastMove=snapshot.lastMove||null; target.active=true; target.engineThinking=Boolean(input.engineThinking??target.engineThinking); target.revision++; target.updatedAt=new Date().toISOString(); return true; }
function stale(response,target,receivedRevision){return json(response,409,{error:'stale state',stale:true,gameId:target.id,expectedRevision:target.revision,receivedRevision});}
function body(req){return new Promise((resolve,reject)=>{let text='';req.on('data',d=>text+=d);req.on('end',()=>{try{resolve(JSON.parse(text||'{}'));}catch{reject(Error('invalid json'));}});});}
function json(response,status,data){response.writeHead(status,{'Content-Type':'application/json'});response.end(JSON.stringify(data));}
function snapshotTurn(target) { return (target.snapshot.fen||' w ').split(/\s+/)[1]||'w'; }
function mutation(req,response,session,kind) { return body(req).then(value=>{ const target=requestedGame(session,value.gameId); if(!target)return json(response,409,{error:'no active game'}); if(session!==target.playerSessionId)return json(response,403,{error:'spectator'}); if(target.result||!target.active)return json(response,409,{error:'game over'}); if(!Number.isInteger(value.revision)||value.revision!==target.revision)return stale(response,target,value.revision); if(kind==='move'&& (target.engineThinking||snapshotTurn(target)!==target.playerColor))return json(response,409,{error:'not your turn'}); if(kind==='engine'&&(!target.engineThinking||snapshotTurn(target)===target.playerColor))return json(response,409,{error:'not engine turn'}); if(!applySnapshot(target,value))return json(response,422,{error:'browser snapshot required'}); emit(target,'move'); if(target.snapshot.result){target.result=target.snapshot.result;target.termination=target.snapshot.termination;end(target,target.result,target.termination);} else if(kind==='move'){target.engineThinking=true;emit(target,'engineThinking');} else target.engineThinking=false; return json(response,200,stateFor(session,target)); }); }
function handle(req,response,session) { const url=new URL(req.url,'http://localhost');
  if(url.pathname==='/events'){const gameId=url.searchParams.get('gameId')||url.searchParams.get('game'); response.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});clients.set(response,{sessionId:session,gameId});response.write(`event: state\ndata: ${JSON.stringify(stateFor(session,gameId?games.get(gameId):games.get(ownedGames.get(session))))}\n\n`);req.on('close',()=>clients.delete(response));return;}
  if(url.pathname==='/api/state')return json(response,200,stateFor(session,url.searchParams.get('gameId')||url.searchParams.get('game')?games.get(url.searchParams.get('gameId')||url.searchParams.get('game')):games.get(ownedGames.get(session))));
  if(req.method==='POST'&&url.pathname==='/api/start')return body(req).then(v=>{const target=start(session,v.color||'random');return target?json(response,200,stateFor(session,target)):json(response,409,{error:'active game'});});
  if(req.method==='POST'&&url.pathname==='/api/move')return mutation(req,response,session,'move');
  if(req.method==='POST'&&url.pathname==='/api/engine-move')return mutation(req,response,session,'engine');
  if(req.method==='POST'&&url.pathname==='/api/resign')return body(req).then(v=>{const target=requestedGame(session,v.gameId);if(!target||session!==target.playerSessionId)return json(response,403,{error:'not player'});if(target.result||!target.active)return json(response,409,{error:'game over'});if(!Number.isInteger(v.revision)||v.revision!==target.revision)return stale(response,target,v.revision);end(target,target.playerColor==='w'?'0-1':'1-0','resign');return json(response,200,{ok:true,gameId:target.id,revision:target.revision,state:stateFor(session,target)});});
  if(!PRODUCTION&&url.pathname==='/engine-test'){const filePath=path.join(root,'public','engine-test.html');if(!fs.existsSync(filePath))return json(response,404,{error:'not found'});response.writeHead(200,{'Content-Type':files['.html']});return fs.createReadStream(filePath).pipe(response);}
  if(!PRODUCTION&&url.pathname==='/test-data/wasm-parity-100.fen'){const filePath=path.resolve(root,'../tests/data/wasm-parity-100.fen');if(!fs.existsSync(filePath))return json(response,404,{error:'not found'});response.writeHead(200,{'Content-Type':'text/plain; charset=utf-8'});return fs.createReadStream(filePath).pipe(response);}
  if(!PRODUCTION&&url.pathname==='/test-data/wasm-parity-100.fen'){const filePath=path.resolve(root,'../tests/data/wasm-parity-100.fen');if(!fs.existsSync(filePath))return json(response,404,{error:'not found'});response.writeHead(200,{'Content-Type':'text/plain; charset=utf-8'});return fs.createReadStream(filePath).pipe(response);}
  if(url.pathname==='/'||url.pathname.startsWith('/public/')){const file=url.pathname==='/'?'index.html':url.pathname.slice(8),filePath=path.join(root,'public',file);if(!filePath.startsWith(PUBLIC_ROOT)||!fs.existsSync(filePath))return json(response,404,{error:'not found'});response.writeHead(200,{'Content-Type':files[path.extname(filePath)]||'text/plain'});return fs.createReadStream(filePath).pipe(response);}
  return json(response,404,{error:'not found'});
}
const server=http.createServer((req,response)=>{const session=cookie(req,response);Promise.resolve(handle(req,response,session)).catch(error=>{if(!response.headersSent)json(response,500,{error:error.message});});});
if(require.main===module)server.listen(PORT,'127.0.0.1',()=>console.log(`HebiChess web listening on http://127.0.0.1:${PORT}`));
module.exports={server,start,currentState:(s,g)=>stateFor(s,g?games.get(g):games.get(ownedGames.get(s))),state:(s,g)=>stateFor(s,g?games.get(g):games.get(ownedGames.get(s))),appendCompletedRecord,boardStart,whitePovEvaluation,getGames:()=>games};
